version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_HOST=postgresdb
    depends_on:
      - postgresdb
    ports:
      - '8000:8000'
    networks:
      - mynetwork

  product-service:
    container_name: product-service
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_HOST=postgresdb
    depends_on:
      - postgresdb
    networks:
      - mynetwork
    ports:
      - '5000:5000'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

  postgresdb:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgresdb
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  database_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
